# List of dns rewrites to use in AdGuardHome
{
    services.adguardhome.settings.filtering.rewrites = [
        {   domain = "ai.uniestro.com";
            answer = "10.20.30.3";
            enabled = true; }
        {   domain = "dns1.uniestro.com";
            answer = "10.20.30.53";
            enabled = true; }
        {   domain = "dns1";
            answer = "10.20.30.53";
            enabled = true; }
        {   domain = "dns2.uniestro.com";
            answer = "10.20.30.35";
            enabled = true; }
        {   domain = "dns2";
            answer = "10.20.30.35";
            enabled = true; }
        {   domain = "g.uniestro.com";
            answer = "10.20.30.3";
            enabled = true; }
        {   domain = "g";
            answer = "10.20.30.3";
            enabled = true; }
        {   domain = "jetkvm.uniestro.com";
            answer = "10.20.30.6";
            enabled = true; }
        {   domain = "jetkvm";
            answer = "10.20.30.6";
            enabled = true; }
        {   domain = "mail.uniestro.net";
            answer = "10.20.30.5";
            enabled = true; }
        {   domain = "mail";
            answer = "10.20.30.5";
            enabled = true; }
        {   domain = "rd.uniestro.com";
            answer = "10.20.30.3";
            enabled = true; }
        {   domain = "rd";
            answer = "10.20.30.3";
            enabled = true; }
        {   domain = "secure.uniestro.com";
            answer = "10.20.30.3";
            enabled = true; }
        {   domain = "secure";
            answer = "10.20.30.3";
            enabled = true; }
        {   domain = "shell.uniestro.com";
            answer = "10.20.30.3";
            enabled = true; }
        {   domain = "shell";
            answer = "10.20.30.3";
            enabled = true; }
        {   domain = "shell1.uniestro.com";
            answer = "10.20.30.53";
            enabled = true; }
        {   domain = "shell2.uniestro.com";
            answer = "10.20.30.35";
            enabled = true; }
        {   domain = "vpn.uniestro.com";
            answer = "10.20.30.3";
            enabled = true; }
        {   domain = "vpn";
            answer = "10.20.30.3";
            enabled = true; }
        {   domain = "vpn-data.uniestro.com";
            answer = "10.20.31.3";
            enabled = true; }
        {   domain = "vpn-data";
            answer = "10.20.31.3";
            enabled = true; }
        {   domain = "unifi";
            answer = "10.20.30.9";
            enabled = true; }
        {   domain = "mail.home.sjau.ch";
            answer = "10.200.0.1";
            enabled = true; }
    ];
}
