# List of dns rewrites to use in AdGuardHome
{
    services.adguardhome.settings.filtering.rewrites = [
        {   domain = "ai.jus-law.ch";
            answer = "10.10.10.7";
            enabled = true; }
        {   domain = "data.jus-law.ch";
            answer = "10.10.10.7";
            enabled = true; }
        {   domain = "docs.jus-law.ch";
            answer = "78.46.32.76";
            enabled = true; }
        {   domain = "ff.jus-law.ch";
            answer = "10.10.10.7";
            enabled = true; }
        {   domain = "g.jus-law.ch";
            answer = "10.10.10.7";
            enabled = true; }
        {   domain = "horde.jus-law.ch";
            answer = "10.10.10.5";
            enabled = true; }
        {   domain = "jetkvm.jus-law.ch";
            answer = "10.10.10.6";
            enabled = true; }
        {   domain = "jetkvm";
            answer = "10.10.10.6";
            enabled = true; }
        {   domain = "mail.jus-law.ch";
            answer = "10.10.10.5";
            enabled = true; }
        {   domain = "shell.jus-law.ch";
            answer = "10.10.10.7";
            enabled = true; }
        {   domain = "voip.jus-law.ch";
            answer = "10.10.10.10";
            enabled = true; }
        {   domain = "vpn.jus-law.ch";
            answer = "10.10.10.7";
            enabled = true; }
        {   domain = "w.jus-law.ch";
            answer = "10.10.10.7";
            enabled = true; }
        {   domain = "www.jus-law.ch";
            answer = "78.46.32.76";
            enabled = true; }


        {   domain = "dns1.sjau.ch";
            answer = "10.10.10.53";
            enabled = true; }
        {   domain = "dns2.sjau.ch";
            answer = "10.10.10.35";
            enabled = true; }
        {   domain = "dns3.sjau.ch";
            answer = "10.10.10.42";
            enabled = true; }
        {   domain = "chem.sjau.ch";
            answer = "10.10.10.3";
            enabled = true; }
        {   domain = "docs.sjau.ch";
            answer = "10.10.10.7";
            enabled = true; }
        {   domain = "ha.sjau.ch";
            answer = "10.10.10.42";
            enabled = true; }
        {   domain = "jetkvm.sjau.ch";
            answer = "10.10.10.4";
            enabled = true; }
        {   domain = "jetkvm-servi";
            answer = "10.10.10.4";
            enabled = true; }
        {   domain = "bazarr.home.sjau.ch";
            answer = "10.10.10.3";
            enabled = true; }
        {   domain = "plex.home.sjau.ch";
            answer = "10.10.10.3";
            enabled = true; }
        {   domain = "servi.home.sjau.ch";
            answer = "10.10.10.3";
            enabled = true; }
        {   domain = "subi.home.sjau.ch";
            answer = "10.10.10.19";
            enabled = true; }
        {   domain = "subidock.home.sjau.ch";
            answer = "10.10.10.18";
            enabled = true; }
        {   domain = "nxfilter.sjau.ch";
            answer = "10.10.10.48";
            enabled = true; }
        {   domain = "pass.sjau.ch";
            answer = "10.10.10.7";
            enabled = true; }
        {   domain = "pics.sjau.ch";
            answer = "10.10.10.3";
            enabled = true; }
        {   domain = "rd.sjau.ch";
            answer = "10.10.10.7";
            enabled = true; }
        {   domain = "shell.sjau.ch";
            answer = "10.10.10.3";
            enabled = true; }
        {   domain = "shell1.sjau.ch";
            answer = "10.10.10.53";
            enabled = true; }
        {   domain = "shell2.sjau.ch";
            answer = "10.10.10.35";
            enabled = true; }
        {   domain = "shell3.sjau.ch";
            answer = "10.10.10.42";
            enabled = true; }
        
        {   domain = "nc.sjau.ch";
            answer = "10.10.10.214";
            enabled = true; }
        {   domain = "g.sjau.ch";
            answer = "10.10.10.214";
            enabled = true; }
        {   domain = "router.sjau.ch";
            answer = "10.10.10.100";
            enabled = true; }
        {   domain = "r.sjau.ch";
            answer = "10.10.10.100";
            enabled = true; }
        {   domain = "wetty.sjau.ch";
            answer = "10.10.10.100";
            enabled = true; }
        {   domain = "o.sjau.ch";
            answer = "10.10.10.50";
            enabled = true; }
        {   domain = "omnia.sjau.ch";
            answer = "10.10.10.50";
            enabled = true; }





        {   domain = "vpn-data.heer-baumgartner.ch";
            answer = "10.100.200.7";
            enabled = true; }
        {   domain = "vpn-mail.heer-baumgartner.ch";
            answer = "10.100.200.5";
            enabled = true; }
        {   domain = "vpn-vpn.heer-baumgartner.ch";
            answer = "10.100.200.1";
            enabled = true; }


        {   domain = "app.scfoodtrendz.com";
            answer = "10.10.10.90";
            enabled = true; }
        {   domain = "cms.scfoodtrendz.com";
            answer = "10.10.10.166";
            enabled = true; }
    ];
}
