# List of dns rewrites to use in AdGuardHome
{
    services.adguardhome.settings.filtering.rewrites = [
        {   domain = "dns.heer-baumgartner.ch";
            answer = "10.100.100.53";
            enabled = true; }
        {   domain = "dns";
            answer = "10.100.100.53";
            enabled = true; }
        {   domain = "router.heer-baumgartner.ch";
            answer = "10.100.100.1";
            enabled = true; }
        {   domain = "router";
            answer = "10.100.100.1";
            enabled = true; }
        {   domain = "mail.heer-baumgartner.ch";
            answer = "10.100.100.5";
            enabled = true; }
        {   domain = "mail";
            answer = "10.100.100.5";
            enabled = true; }
        {   domain = "www.heer-baumgartner.ch";
            answer = "10.100.100.5";
            enabled = true; }
        {   domain = "www";
            answer = "10.100.100.5";
            enabled = true; }
        {   domain = "data.heer-baumgartner.ch";
            answer = "10.100.100.7";
            enabled = true; }
        {   domain = "data";
            answer = "10.100.100.7";
            enabled = true; }
        {   domain = "jetkvm.heer-baumgartner.ch";
            answer = "10.100.100.6";
            enabled = true; }
        {   domain = "jetkvm";
            answer = "10.100.100.6";
            enabled = true; }
        {   domain = "pw.heer-baumgartner.ch";
            answer = "10.100.100.7";
            enabled = true; }
        {   domain = "pw";
            answer = "10.100.100.7";
            enabled = true; }
        {   domain = "g.heer-baumgartner.ch";
            answer = "10.100.100.7";
            enabled = true; }
        {   domain = "g";
            answer = "10.100.100.7";
            enabled = true; }
        {   domain = "docs.heer-baumgartner.ch";
            answer = "10.100.100.7";
            enabled = true; }
        {   domain = "docs";
            answer = "10.100.100.7";
            enabled = true; }
        {   domain = "voip.heer-baumgartner.ch";
            answer = "10.100.100.10";
            enabled = true; }
        {   domain = "voip";
            answer = "10.100.100.10";
            enabled = true; }
        {   domain = "voip.heer-baumgartner.ch";
            answer = "10.100.100.10";
            enabled = true; }
        {   domain = "shell.heer-baumgartner.ch";
            answer = "10.100.100.7";
            enabled = true; }
        {   domain = "shell1.heer-baumgartner.ch";
            answer = "10.100.100.53";
            enabled = true; }
        {   domain = "vpn-data.heer-baumgartner.ch";
            answer = "10.100.200.7";
            enabled = true; }
    ];
}
